# version format
version: 0.2.1.{build}

image: Visual Studio 2019

cache:
  - packages -> src\**\packages.config              # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

configuration: Release

branches:
  only:
    - develop
    - master

environment:
  # Version Suffix
  version_suffix: alpha

install:
  - ps: .\build\appveyor-semver.ps1
  - ps: .\build\check-release-version.ps1
  - ps: Update-AppveyorBuild -Version $Env:appveyor_version

assembly_info:
  patch: true
  file: 'source\Novicell.Examine.ElasticSearch**\AssemblyInfo.*'
  assembly_version: '$(appveyor_file_version)'
  assembly_file_version: '$(appveyor_file_version)'
  assembly_informational_version: '$(mssemver)'



build_script:
- cmd: >-
    build-appveyor.cmd

    cd..

artifacts:
  - path: artifacts\*.nupkg
  - path: artifacts\*.zip


deploy:
- provider: NuGet
  server: https://nuget.novicell.london/nuget
  api_key:
    secure: A/xkn1/+F9+HTwGVLEPRFDwDSDMZLJ2zl1AnqsKOoE9tlYio2wrFBUN9BJkZw5aTmNsKy7Yjn6lbS61KSnuXHQ==
  artifact: /.*\.nupkg/
- provider: GitHub
  tag: GH Pre-Release
  auth_token:
    secure: CnPbSuXiCJXBzQur6JGaYPrx/HCnLJljBT3hpyGrBlxK7vTKPWhnG+dlr2H/4f2Q
  repository: Novicell/Novicell.Examine.ElasticSearch
  artifact: .*\*
  draft: true
  prerelease: true
  on:
    branch: development
- provider: GitHub
  tag: GH Pre-Release
  auth_token:
    secure: CnPbSuXiCJXBzQur6JGaYPrx/HCnLJljBT3hpyGrBlxK7vTKPWhnG+dlr2H/4f2Q
  repository: Novicell/Novicell.Examine.ElasticSearch
  on:
    branch: master
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: tech-nuget-london
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true