# version format
version: 1.7.2.{build}

os: Visual Studio 2017

cache:
  - packages -> src\**\packages.config              # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

configuration: Release

branches:
  only:
    - develop
    - master

environment:
  # Version Suffix
  version_suffix: alpha

install:
  - ps: .\build\appveyor-semver.ps1
  - ps: .\build\check-release-version.ps1
  - ps: Update-AppveyorBuild -Version $Env:appveyor_version

assembly_info:
  patch: true
  file: 'source\nuPickers**\AssemblyInfo.*'
  assembly_version: '$(appveyor_file_version)'
  assembly_file_version: '$(appveyor_file_version)'
  assembly_informational_version: '$(mssemver)'

build_script:
- cmd: >-
    build-appveyor.cmd

    cd..

artifacts:
  - path: artifacts\*.nupkg
  - path: artifacts\*.zip


deploy:
    # MyGet Deployment for builds
  - provider: NuGet
    server: https://www.myget.org/F/nupickers/
    symbol_server: https://www.myget.org/F/nupickers/symbols/api/v2/package
    api_key:
      secure: SASQGWG/4zNns7bwSSsJ5RPvKcKfJsBeEPuw69wsVPA3PO739QmzVtc5VwQwgvbr
    artifact: /.*\.nupkg/
    on:
      branch: develop

    # MyGet Deployment for releases
  - provider: NuGet
    server: https://www.myget.org/F/nupickers/
    symbol_server: https://www.myget.org/F/nupickers/symbols/api/v2/package
    api_key:
      secure: SASQGWG/4zNns7bwSSsJ5RPvKcKfJsBeEPuw69wsVPA3PO739QmzVtc5VwQwgvbr
    artifact: /.*\.nupkg/
    on:
      branch: master

     # NuGet Deployment for releases
  - provider: NuGet
    server:
    api_key:
      secure: adk3pI9HCByZg2VRxplX9UR6qHf97bA3as6dusxLswCKI8BQQE8DO5a0frLrI+EO
    artifact: /.*\.nupkg/
    on:
      branch: master
      appveyor_repo_tag: true        # deploy on tag push only

     # GitHub Deployment for releases
  - provider: GitHub
    auth_token:
      secure: c0LwOGqoFZIieyy8CHrUtYQOD0HL0rG5tV2DS+8FHv34BKs/LSGGtmWWep5O7GbV
    artifact: /.*\.zip/            # upload all Zip packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true        # deploy on tag push only
